### PR TITLE
Use isomorphic-style-loader to render <style> on server

### PR DESCRIPTION
**Pull request by dsernst**
Use https://github.com/kriasoft/isomorphic-style-loader to render critical styles on the server, without needing an extra http request nor loading styles for unused components.

This closes https://github.com/koistya/react-static-boilerplate/issues/28 and builds off the work from https://github.com/kriasoft/isomorphic-style-loader/issues/5. This would also supersede PR https://github.com/koistya/react-static-boilerplate/pull/41 and close https://github.com/koistya/react-static-boilerplate/issues/34.

### CODE REVIEW

**Comment by dsernst** [comment]
Most of this was implemented by using https://github.com/kriasoft/react-starter-kit as an example.

**Comment by dsernst** [comment]
One piece that's missing is a separate `context.insertCss` for client as @koistya describes [here](https://github.com/kriasoft/isomorphic-style-loader/issues/5#issuecomment-171620472):

> `(styles) => styles._insertCss()` for client-side code and `(styles) => { css.push(styles._getCss(); }` for server-side code.

Right now, all that's implemented is the server version: https://github.com/koistya/react-static-boilerplate/pull/64/files#diff-0364f57fbff2fabbe941ed20c328ef1aR22

Since this project doesn't have separate `client.js` and `server.js` files like `react-starter-kit`, it wasn't clear to me how define these separately.

With that said, Hot Module Replacement seems to be working fine.

**Comment by dsernst** [comment]
For some reason, this seems to be interrupting `Link.handleClick`. Now it causes a full page refresh, instead of just a client-side transitionTo. Any idea how that could be related, @koistya?

**Comment by dsernst** [comment]
Ok, the Link.handleClick was broken by [wrapping `Link`](https://github.com/dsernst/react-static-boilerplate/commit/32dd998f7ac931438143036823bc5f82dbf5ffeb#diff-650133b9371322c70ec3660623677c43R62) with `withStyles`:

```
Uncaught TypeError: _Link2.default.handleClick is not a function
```

**Comment by dsernst** [comment]
@koistya is it important to use this async version

```js
componentWillUnmount() {
  setTimeout(this.removeCss, 0);
}
```

[here](https://github.com/koistya/react-static-boilerplate/pull/64/files#diff-61ea760c66f6325f15bdf37f5288fe91R36) and [here](https://github.com/koistya/react-static-boilerplate/pull/64/files#diff-69a4ff9bb10f4df2946e1445f0f11708R14)?

(following your example here: https://github.com/kriasoft/isomorphic-style-loader/commit/857200eb20492e2ebedaf91d1dc0fcec1ff527df#commitcomment-15633683)

**Comment by dsernst** [comment]
The [pre-rendered `<style>` block](https://github.com/dsernst/react-static-boilerplate/commit/ef8efe697cf37bf0ee15cdb304afaa09a29cf2a5#diff-e2162b02490cdeb5638a67fb1652a34fR23) never gets removed, so effectively all of the css for the initial page appears in the DOM twice. It doesn't seem to be causing any functional issues, but may not be what you intended, @koistya.

**Comment by dsernst** [comment]
I've deployed this, and all seems to be working great. There's a noticeable speedup, & getting rid of the FOUC is :+1: :+1: :+1:

**Comment by webyak** [comment]
Any updates on this?

**Comment by dsernst** [comment]
It's been working great in production for the last 2 months :+1:

**Comment by pierrecholhot** [comment]
@dsernst I was trying to implement this on my fork when I noticed that it actually duplicates the styles if the component is present more than once on the page.

1- Git Checkout `iso-styles` branch
2- Npm install
3- Open Layout.js, and duplcate the `<Navigation />` line a couple of times.

Result: The same styles are present more than once.

Is there a way to fix this ?

**Comment by pierrecholhot** [comment]
@dsernst, I found a solution; Not very elegant, but it does the job.

**Filter duplicated CSS in `render.js`:**

```
  import _ from 'lodash';

  ...

  const data = {
    ...
    body: ReactDOM.renderToStaticMarkup(component),
    css: _.uniq(css).join('\n')
  };
```

Works great. Now when I have 9 <Link /> Components on my page, I dont have 9 duplicated CSS blocks in the header.

**Comment by pierrecholhot** [comment]
Regarding the pre-rendered style block issue, indeed it's a minor annoyance while developing.
This can be fixed by removing it when the DOM is ready..

```
const container = document.getElementById('app');

location.listen(location => {
  const loc = location.pathname;
  route(loc, async (component) => ReactDOM.render(component, container, () => {
    // Track the page view event via Google Analytics
    window.ga('send', 'pageview');
    // Clean-up FOUC css
    document.head.removeChild(document.getElementById('css'));
  }));
});
```

**Comment by koistya** [comment]
@dsernst great PR! Need to find a way to merge it. I have disabled pre-rendering for now, to make it easier to update the code to the latest versions of all the dependencies. But it might be a good idea to bring pre-rendering back including critical CSS rendering as you proposed.

**Comment by koistya** [comment]
RSB is currently taking an alternative direction when the initial page load time is optimized by using code splitting, similar to what Facebook guys are using. Check the [demo](https://rsb.kriasoft.com). Though, `isomorphic-style-loader` still can be useful because it allows injecting only the CSS that is actually used by mounted React components (as opposed to `style-loader` which injects everything and don't clean up unused styles after components unmounted).

**Pull request closed without merging**
