### PR TITLE
Add service workers for offline app use

### PR DESCRIPTION
**Pull request by t-kelly**
Clone and give it a try! Navigate to `/` and `/about`, disconnect from the internet, and refresh the page. Everything still works!

- Pages that are chunked via webpack will only be available offline after then have been visited/downloaded. As a result, we might want to provide developers with more control over which pages are chunked and which are included in `main.js`. To do this, I added a `chunk` property to `routes.json` which will be used to set whether or not the route will be chunked.

Unfortunately, I can't seem to get the npm module for UpUp to work well so I had to include the files statically. This could obviously use some improvement.

Thoughts?

### CODE REVIEW

**Comment by koistya** [comment]
This looks really interesting! I will test it after coming back from my trip on Tuesday-Wednesday.

**Comment by v3yr0n** [comment]
THAT IS AWESOME!  :)

**Comment by koistya** [comment]
@t-kelly great idea with the `chunk` property in routes! I just have added this functionality in a201611, just replaced `boolean` type with a `string`, this way you can also group multiple routes into the same chunks by given them names. See https://github.com/webpack/webpack/tree/master/examples/named-chunks

**Comment by t-kelly** [comment]
@koistya Nice! Good idea.

**Pull request closed without merging**
