### PR TITLE
create a css file for production build

### PR DESCRIPTION
**Pull request by kevinsproles**
Better for SEO. Page can load with JS disabled.

Resolves https://github.com/koistya/react-static-boilerplate/issues/34

Also made JS async, therefore static page is first class citizen for maximum performance. The react app loads when it loads, doesn't hold up the perceived page performance.

### CODE REVIEW

**Comment by kevinsproles** [comment]
I don't what the build failures are all about. Most are not on files I changed. Let me know what you'd like me to do about that.

**Comment by kevinsproles** [comment]
@koistya thoughts?

**Comment by weisjohn** [comment]
@koistya  I can confirm this PR works well. I just tested it.

@kevinsproles - Thanks so much for submitting that. I am super new to webpack, and it really helped me out.

**Comment by koistya** [comment]
@kevinsproles cool, thanks! Looks good to me. An alternative solution is to use `isomorphic-style-loader` which can help generate CSS for each page, only what is actually used on each web page, and embed that into HTML (pros: (1) no extra HTTP request needed like in case with `ExtractTextPlugin` and a separate `.css` file, (2) webpage will initially load CSS that is actually used on that particular page as opposed to downloading CSS for the whole site, (3) CSS DOM will contain only CSS that is actually used, when user switches between pages, unused CSS will be removed from CSS DOM).

**Comment by koistya** [comment]
@kevinsproles, @weisjohn sorry, I totally forgot about this PR. It's definitely a good one, needs to be merged. I will try to resolve the conflicts.

**Comment by koistya** [comment]
RSB is currently taking an alternative direction, when the initial page load time is optimized by using code splitting, similar to what Facebook guys are using. Check the [demo](https://rsb.kriasoft.com).

**Pull request closed without merging**
